[package]
name = "filehost"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.6"
actix-multipart = "0.6"
actix-web = "4"
bytesize = "2.0.1"
humanize-bytes = "1.0.6"
serde_json = "1.0.140"
tiny_id = "0.1.6"
